version: '4'
services:
  postgres:
    image: postgres
    container_name: company_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5433:5433"
    volumes:
      - ./postgres:/data/postgres